### ISSUE TITLE
Technical Information about XSD 2 OWL mappings

### ISSUE THREAD

**Issue by juandm** [srdc/ontmalizer#17]
Hi there,

Im trying to find the mapping rules you used to convert from XSD to OWL but the link in description is not working anymore (http://blog.salusproject.eu/?p=189.), is there a new site with this information? 

Thanks in advance

**Comment by msfyuksel** [comment]
Hi,

Sorry for the domain name issue. You can access the link at http://www.srdc.com.tr/projects/salus/blog/?p=189. I am also updating the readme now. 

Best,
Mustafa

**Comment by juandm** [comment]
Thanks for the reply!
